version: '3.9'

networks:
  sso:
    name: sso
    driver: bridge

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "44044:44044"
    networks:
      - sso

  postgres-sso:
    image: postgres:17
    container_name: postgres-sso
    restart: unless-stopped
    environment:
      POSTGRES_USER: sso
      POSTGRES_PASSWORD: sso
      POSTGRES_DB: sso
      PGDATA: /var/lib/postgresql/data
    volumes:
      - sso-pgdata:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=1000
              -c shared_buffers=256MB
              -c effective_cache_size=768MB
              -c maintenance_work_mem=64MB
              -c checkpoint_completion_target=0.7
              -c wal_buffers=16MB
              -c default_statistics_target=100
    ports:
      - "5432:5432"
    networks:
      - sso
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sso -d sso" ]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true

volumes:
  sso-pgdata:
    driver: local